
version: '3.9'

services:
  dash:
    command: tail -f /dev/null
    image: chanphot/car_price_prediction01_st124877
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9001:80
    environment:
      - HOST=0.0.0.0
      - PORT=80