name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Create the service account key file directly in the workflow
    - name: Create Service Account Key File
      run: |
        cat <<EOF > sa_key.json
        {
          "type": "service_account",
          "project_id": "ridesafe-443408",
          "private_key_id": "c1600c378b4838c8bdb0fa82974176e0ab9660c1",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCl+TStRXBk0+mV\niZ7bpkRJzazEbc4l/XANwO2LK4cyDMEP3mQiJnWG9eEKWz5W6wbZYrL2P1f/KWQx\n....\n-----END PRIVATE KEY-----\n",
          "client_email": "wong-472@ridesafe-443408.iam.gserviceaccount.com",
          "client_id": "106706179221806356732",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/wong-472%40ridesafe-443408.iam.gserviceaccount.com",
          "universe_domain": "googleapis.com"
        }
        EOF

    # Authenticate Docker with GCR
    - name: Authenticate Docker with GCR
      run: |
        gcloud auth activate-service-account --key-file=sa_key.json
        gcloud auth configure-docker gcr.io

    # Debug step to verify authentication
    - name: Verify GCloud Authentication
      run: |
        gcloud auth list

    # Debug step to check IAM roles
    - name: Check IAM Policy
      run: |
        gcloud projects get-iam-policy ridesafe-443408

    # Build Docker image for your Dash app
    - name: Build Docker image
      run: |
        docker build -t gcr.io/ridesafe-443408/ride_safe_dashboard:${{ github.sha }} .

    # Push Docker image to Google Container Registry
    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/ridesafe-443408/ride_safe_dashboard:${{ github.sha }}



